server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/Applications/IntelliJ IDEA.app/Contents/bin/identifier.sqlite
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: com.example.boot.configuration.SQLiteDialect
    open-in-view: false